core/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

funcionarios/urls.py
from django.urls import path
from .views import FuncionariosList, FuncionarioEdit, FuncionarioDelete, FuncionarioNovo, relatorio_funcionario

urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioNovo.as_view(), name='create_funcionario'),
    path('editar/<int:pk>/', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('deletar/<int:pk>/', FuncionarioDelete.as_view(), name='delete_funcionario'),
    path('relatorio-funcionario', relatorio_funcionario, name='relatorio_funcionario'),
]

gestao_rh/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from funcionarios.api.views import FuncionarioViewSet
from hora_extra.api.views import HoraExtraViewSet

router = routers.DefaultRouter()
router.register(r'api/funcionarios', FuncionarioViewSet)
router.register(r'api/banco-horas', HoraExtraViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('funcionarios/', include('funcionarios.urls')),
    path('depatarmentos/', include('departamentos.urls')),
    path('empresas/', include('empresas.urls')),
    path('documentos/', include('documentos.urls')),
    path('hora-extra/', include('hora_extra.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

documentos/models.py
from django.db import models
from django.urls import reverse

from funcionarios.models import Funcionario

class Documentos(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models import Sum

from departamentos.models import Departamentos
from empresas.models import Empresas


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamentos)
    empresa = models.ForeignKey(Empresas, on_delete=models.PROTECT, null=True, blank=True)
    imagem = models.ImageField()

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    @property
    def total_horas_extra(self):
        total = self.horaextra_set.all().aggregate(Sum('horas'))['horas__sum']
        return total or 0

    def __str__(self):
        return self.nome

hora_extra/models.py
from django.db import models
from django.urls import reverse

from funcionarios.models import Funcionario


class HoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizado = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.funcionario.id])

    def __str__(self):
        return self.motivo

funcionarios/api/views.py
from rest_framework import viewsets
from funcionarios.api.serializers import FuncionarioSerializer
from funcionarios.models import Funcionario
from rest_framework.permissions import IsAuthenticated
from rest_framework.authentication import TokenAuthentication


class FuncionarioViewSet(viewsets.ModelViewSet):
    queryset = Funcionario.objects.all().order_by()
    serializer_class = FuncionarioSerializer
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)

funcionarios/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse, FileResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
import io
from reportlab.pdfgen import canvas

from .models import Funcionario


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
        empresa_logada = self.request.user.funcionario.empresa
        return Funcionario.objects.filter(empresa= empresa_logada)


class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']


class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')


class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):
        funcionario = form.save(commit=False)
        username = funcionario.nome.split(' ')[0] + funcionario.nome.split(' ')[1]
        funcionario.empresa = self.request.user.funcionario.empresa
        funcionario.user = User.objects.create(username=username)
        funcionario.save()
        return super(FuncionarioNovo, self).form_valid(form)

def relatorio_funcionario(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)

    p.drawString(200, 810, 'Relatorio de funcionarios')

    # palavras = ['palavra1', 'palavra2', 'palavra3']
    funcionarios = Funcionario.objects.filter(empresa= request.user.funcionario.empresa)

    texto = 'Nome: %s  '

    y = 750
    for funcionario in funcionarios:
        p.drawString(10, y, texto % (funcionario.nome))
        y -= 20

    p.showPage()
    p.save()

    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)
    return response

funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}
<form method="POST">
  {% csrf_token %}
  <h1>Você tem certeza que quer deletar {{ funcionario }}? </h1>
  {{form}}

  <button type="submit" class="btn btn-danger">Comfirmar</button>
</form>

{% endblock %}

funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}
edit

<form method="POST">
  {% csrf_token %}

  {{form|bootstrap}}

  <button type="submit" class="btn btn-info">Salvar</button>
</form>
<br>
<h2>Documentos</h2>
<ul>
  {% for documento in object.documentos_set.all %}
    <li>
      <a href="{{ documento.arquivo.url }}">{{ documento.descricao }}</a><br>
    </li>
  {% endfor %}
</ul>
<br>
<a href="{% url 'create_documento' object.id %} " class="btn btn-success">Adicionar arquivos</a>

<br>
<h2>Banco de Horas</h2>
<ul>
  {% for hora in object.horaextra_set.all %}
    <li>
      <a href="{% url 'update_hora_extra' hora.id %}">{{ hora.motivo }} | {{ hora.horas }}</a><br>
    </li>
  {% endfor %}
</ul>
<br>
<h3>Total Hora Extra: {{ object.total_horas_extra }}</h3>

{% endblock %}

funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}
    List
    {% for funcionario in object_list %}
        <br>
        <a href="{% url 'update_funcionario' funcionario.id%}">{{funcionario}}</a>
        <a href="{% url 'delete_funcionario' funcionario.id%}">deletar</a>
    {%endfor%}
    <br>
    <a href="{% url 'create_funcionario' %}" class="btn btn-info">Novo</a>
    <a href="{% url 'relatorio_funcionario' %}" class="btn btn-info">Gerar PDF Funcionarios</a>
{% endblock %}